
# UseUtil.cmake
# defines CUBIT_UTIL_DEFINES for definitions for building with cubit_util
# and automatically adds -D defintions for using util


IF(CMAKE_SYSTEM MATCHES "Linux")
SET(CUBIT_UTIL_DEFINES "-DTEMPLATE_DEFS_INCLUDED -DCUBIT_LINUX" CACHE INTERNAL "")
SET(TEMPLATE_DEFS_INCLUDED CACHE INTERNAL "")
ENDIF(CMAKE_SYSTEM MATCHES "Linux")

IF(CMAKE_SYSTEM MATCHES "Darwin")
SET(CUBIT_UTIL_DEFINES "-DTEMPLATE_DEFS_INCLUDED -DMACOSX" CACHE INTERNAL "")
SET(TEMPLATE_DEFS_INCLUDED CACHE INTERNAL "")
ENDIF(CMAKE_SYSTEM MATCHES "Darwin")

IF(WIN32)
SET(CUBIT_UTIL_DEFINES "-DTEMPLATE_DEFS_INCLUDED -DNT" CACHE INTERNAL "")
SET(TEMPLATE_DEFS_INCLUDED CACHE INTERNAL "")
ENDIF(WIN32)

IF(CMAKE_SYSTEM MATCHES "SunOS")
SET(CUBIT_UTIL_DEFINES "-DSUN -DSOLARIS" CACHE INTERNAL "")
ENDIF(CMAKE_SYSTEM MATCHES "SunOS")

IF(CMAKE_SYSTEM MATCHES "IRIX")
SET(CUBIT_UTIL_DEFINES "-DSGI" CACHE INTERNAL "")
ENDIF(CMAKE_SYSTEM MATCHES "IRIX")

IF(CMAKE_SYSTEM MATCHES "HP-UX")
SET(CUBIT_UTIL_DEFINES "+Z -DHP -DCANT_USE_STD -DCANT_USE_STD_IO -DTEMPLATE_DEFS_INCLUDED" CACHE INTERNAL "")
SET(TEMPLATE_DEFS_INCLUDED CACHE INTERNAL "")
ENDIF(CMAKE_SYSTEM MATCHES "HP-UX")

ADD_DEFINITIONS(${CUBIT_UTIL_DEFINES})


